<a href="https://colab.research.google.com/github/Niyati223/Niyati223/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
ages_list=[10,5,8,32,65,43]
print(ages_list)

[10, 5, 8, 32, 65, 43]


There are 3 main ways to instantiate a Numpy ndarray object. One of these is to use np.array(<'collection'>)

In [ ]:
ages=np.array(ages_list)
print(type(ages))
print(ages)

<class 'numpy.ndarray'>
[10  5  8 32 65 43]


In [ ]:
print(ages)
print('size:\t',ages.size)
print('shape:\t',ages.shape)

[10  5  8 32 65 43]
size:	 6
shape:	 (6,)


In [ ]:
zeroArr=np.zeros(5)
print(zeroArr)


[0. 0. 0. 0. 0.]


Multi Dimension

In [ ]:
weight_list=[32,18,26,60,55,65]
print(weight_list)
print(type(weight_list))

[32, 18, 26, 60, 55, 65]
<class 'list'>


In [ ]:
people=np.array([ages_list,weight_list])
print(people)

[[10  5  8 32 65 43]
 [32 18 26 60 55 65]]


In [ ]:
#shape and size
print('people:\t',people)
print('size:\t',people.size)
print('shape:\t',people.shape)

people:	 [[10  5  8 32 65 43]
 [32 18 26 60 55 65]]
size:	 12
shape:	 (2, 6)


In [ ]:
#reshape
#creating 12 dimensions and that should have a single element and for that we use reshape
people=people.reshape(12,1)
print('people:\t',people)

people:	 [[10]
 [ 5]
 [ 8]
 [32]
 [65]
 [43]
 [32]
 [18]
 [26]
 [60]
 [55]
 [65]]


In [ ]:
#check the size of reshaped and shape of it
print('size:\t',people.size)
print('shape:\t',people.shape)

size:	 12
shape:	 (12, 1)


Exercise

Generate a 1D numpy array with the values [7, 9, 65, 33, 85, 99]

In [ ]:
import numpy as np
arr=np.array([7, 9, 65, 33, 85, 99])
print(arr)

[ 7  9 65 33 85 99]


In [ ]:
print('size:\t',arr.size)
print('shape:\t',arr.shape)

size:	 6
shape:	 (6,)


Generate a matrix (2D numpy array) of the values

In [ ]:
two=np.array([[1,2,4],[2,3,0],[0,5,1]])
print(two)

[[1 2 4]
 [2 3 0]
 [0 5 1]]


In [ ]:
print('size:\t',two.size)
print('shape:\t',two.shape)

size:	 9
shape:	 (3, 3)


Change the dimensions of this array to another permitted shape

In [ ]:
two=two.reshape(9,1)
print(two)

[[1]
 [2]
 [4]
 [2]
 [3]
 [0]
 [0]
 [5]
 [1]]


In [ ]:
two=two.reshape(9,)
print(two)

[1 2 4 2 3 0 0 5 1]


Array Generation

The np.arange() method creates a range of numbers with user defined steps between each.

In [ ]:
five_table=np.arange(0,56,5)
print(five_table)

[ 0  5 10 15 20 25 30 35 40 45 50 55]


The np.linspace() method will produce a range of evenly spaced values, starting, ending, and taking as many steps as you specify.

In [ ]:
five_space=np.linspace(0,40,11)
print(five_space)

[ 0.  4.  8. 12. 16. 20. 24. 28. 32. 36. 40.]


In [ ]:
five_space=np.linspace(0,50,11)
print(five_space)

[ 0.  5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


The .repeat() method will repeat an object you pass a specified number of times.

In [ ]:
twoarr=np.repeat(2,10)
print(twoarr)

[2 2 2 2 2 2 2 2 2 2]


In [ ]:
threearr=np.repeat(3,5)
print(threearr)

[3 3 3 3 3]


The np.eye() functions will create an identity matrix/array for us.

In [ ]:
identity_matrix = np.eye(6)
print(identity_matrix)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [ ]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Operations

There are many, many operations which we can perform on arrays. Below, we demonstrate a few

In [ ]:
five_table

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

In [ ]:
print(five_table)

[ 0  5 10 15 20 25 30 35 40 45 50 55]


In [ ]:
print("1:", 2 * five_table)
print("2:", 10 + five_table)
print("3:", five_table - 1)
print("4:", five_table/5)
print("5:", five_table **2)
print("6:", five_table < 20)

1: [  0  10  20  30  40  50  60  70  80  90 100 110]
2: [10 15 20 25 30 35 40 45 50 55 60 65]
3: [-1  4  9 14 19 24 29 34 39 44 49 54]
4: [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
5: [   0   25  100  225  400  625  900 1225 1600 2025 2500 3025]
6: [ True  True  True  True False False False False False False False False]


Speed Test


If we compare the speed at which we can do these operations compared to core python, we will notice a substantial difference.

In [ ]:
fives_list = list(range(0,50,5))
fives_list

[0, 5, 10, 15, 20, 25, 30, 35, 40, 45]

In [ ]:
five_list_lge=np.arange(0,40,5)
print(five_list_lge)

[ 0  5 10 15 20 25 30 35]


In [ ]:
%timeit five_list_lge + 5

736 ns ± 5.5 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [ ]:
%timeit [e + 5 for e in fives_list]

562 ns ± 6.47 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


Boolean string operations can also be performed on ndarrays.

In [ ]:
words=np.array(['nine','eight','seven','six'])
print(np.isin(words,'e'))

print('e' in words)
['e' in w for w in words]

[False False False False]
False


[True, True, True, False]

Transpose

In [ ]:
people.shape = (2, 6)
print(people, "\n")
print(people.T)

[[10  5  8 32 65 43]
 [32 18 26 60 55 65]] 

[[10 32]
 [ 5 18]
 [ 8 26]
 [32 60]
 [65 55]
 [43 65]]


Data Types

As previously mentioned, ndarrays can only have one data type. If we want to obtain or change this, we use the .dtype attribute.

In [ ]:
people.dtype

dtype('int64')

What is the data type of the below ndarray?

In [ ]:
ages_with_strings = np.array([10, 5, 8, '32', '65', '43'])
ages_with_strings


array(['10', '5', '8', '32', '65', '43'], dtype='<U21')

In [ ]:
ages_with_strings = np.array([10, 5, 8, '32', '65', '43'])
print(ages_with_strings)

['10' '5' '8' '32' '65' '43']


What is the dtype of this array?

In [ ]:
ages_with_strings = np.array([10, 5, 8, '32', '65', '43'], dtype='int32')
ages_with_strings

array([10,  5,  8, 32, 65, 43], dtype=int32)

What do you think has happened here?

In [ ]:
ages_with_strings = np.array([10, 5, 8, '32', '65', '43'])
print(ages_with_strings)

['10' '5' '8' '32' '65' '43']


In [ ]:
ages_with_strings.size

6

In [ ]:
ages_with_strings.dtype

dtype('<U21')

In [ ]:
ages_with_strings.dtype = 'int32'
print(ages_with_strings)

[49 48  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 53  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 56  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 51 50  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0 54 53  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0 52 51  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0]


In [ ]:
ages_with_strings.dtype

dtype('int32')

In [ ]:
ages_with_strings.size

126

In [ ]:
ages_with_strings.size/21

6.0

In [ ]:
np.array([10, 5, 8, '32', '65', '43']).size

6

The correct way to have changed the data type of the ndarray would have been to use the .astype() method, demonstrated below.

In [ ]:
ages_with_string=np.array([10,5,8,'32','65','43'])
print(ages_with_string)
print(ages_with_string.astype('int32'))

['10' '5' '8' '32' '65' '43']
[10  5  8 32 65 43]


Exercise

Create an array of string numbers, but use dtype to make it an array of floats

In [ ]:
string_array=np.array(['20','30','40','50','60'],dtype='float32')
string_array


array([20., 30., 40., 50., 60.], dtype=float32)

In [ ]:
string_array=np.array(['20','30','40','50','60'],dtype='float32')
print(string_array)


[20. 30. 40. 50. 60.]


Transpose the matrix, printing the new size and shape.

In [ ]:
string_array.shape=(1,5)
print(string_array,'\n')
print(string_array.T)
print(string_array.size)

[[20. 30. 40. 50. 60.]] 

[[20.]
 [30.]
 [40.]
 [50.]
 [60.]]
5


Use the .astype() method to convert the array to boolean.

In [ ]:
print(string_array)
print(string_array.astype('bool'))

[[20. 30. 40. 50. 60.]]
[[ True  True  True  True  True]]


Array Slicing Operations

As before, we can use square brackets and indices to access individual values, and the colon operator to slice the array.

In [ ]:
fives_list

[0, 5, 10, 15, 20, 25, 30, 35, 40, 45]

In [ ]:
fives_list[0]

0

In [ ]:
fives_list[-1]

45

In [ ]:
fives_list[:4]

[0, 5, 10, 15]

In [ ]:
fives_list[4:]

[20, 25, 30, 35, 40, 45]

We can also slice an n-dim ndarray., specifying the slice operation accross each axis.

In [ ]:
print(people)
print(people[:3,:3])

[[10  5  8 32 65 43]
 [32 18 26 60 55 65]]
[[10  5  8]
 [32 18 26]]


Exercise

Create a numpy array with 50 zeros

In [ ]:

zeroarr=np.zeros(50)
print(zeroarr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0.]


Create a np array of 2 repeated 20 times

In [ ]:
twoarrr=np.repeat(2,21)
print(twoarrr)

[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


Create a numpy array from 0 to 2 pi  in steps of 0.1

In [ ]:
z=np.arange(0,2*3.141,0.1)
print(z)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5
 3.6 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3
 5.4 5.5 5.6 5.7 5.8 5.9 6.  6.1 6.2]


Get the first five values

In [ ]:
four_list=np.arange(0,40,4)
print(four_list)

[ 0  4  8 12 16 20 24 28 32 36]


In [ ]:
print(four_list[:5])


[ 0  4  8 12 16]


Get the last 3 values

In [ ]:
four_list[-3]

28

Get the 4th value to the 7th value

In [ ]:
print(four_list[4:7])

[16 20 24]


We can reverse an array by using .flip() or by using the :: operator.

In [ ]:
print(fives_list)
reverse_fives_list=np.flip(fives_list)
print(reverse_fives_list)


[0, 5, 10, 15, 20, 25, 30, 35, 40, 45]
[45 40 35 30 25 20 15 10  5  0]


In [ ]:
print(fives_list)
reverse_fives_list=fives_list[-1::-1]
print(reverse_fives_list)

[0, 5, 10, 15, 20, 25, 30, 35, 40, 45]
[45, 40, 35, 30, 25, 20, 15, 10, 5, 0]


We can also use the :: operator to select steps of the original array.

In [ ]:
fives_list[0::3]

[0, 15, 30, 45]

Exercise

Take one of the arrays you defined and Reverse it

In [ ]:
print(four_list)
reverse_four_list=np.flip(four_list)
print(reverse_four_list)


[ 0  4  8 12 16 20 24 28 32 36]
[36 32 28 24 20 16 12  8  4  0]


 Only keep every 4th element.

In [ ]:
print(four_list)
four_list[4::4]

[ 0  4  8 12 16 20 24 28 32 36]


array([16, 32])

Get every 2nd element, starting from the last and moving backwards.

In [ ]:
print(four_list)
print(four_list[-2::-2])

[ 0  4  8 12 16 20 24 28 32 36]
[32 24 16  8  0]


Stats

In [ ]:
np.array([1.65432, 5.98765]).round(2)

array([1.65, 5.99])

In [ ]:
nums = np.arange(0, 4, 0.2555)
print(nums)

[0.     0.2555 0.511  0.7665 1.022  1.2775 1.533  1.7885 2.044  2.2995
 2.555  2.8105 3.066  3.3215 3.577  3.8325]


Exercise

Compute min, max, sum, mean, median, variance, and standard deviation of the above array, all to to 2 decimal places.

In [ ]:
print("min = ", np.min(nums).round(2))
print("max = ", np.max(nums).round(2))
print("sum = ", np.sum(nums).round(2))
print("mean = ", np.mean(nums).round(2))
print("median = ", np.median(nums).round(2))
print("var = ", np.var(nums).round(2))
print("std = ", np.std(nums).round(2))

min =  0.0
max =  3.83
sum =  30.66
mean =  1.92
median =  1.92
var =  1.39
std =  1.18


Random

With np.random, we can generate a number of types of dataset, and create training data.

The below code simulates a fair coin toss.

In [ ]:
flip = np.random.choice([0,1], 10)
flip


array([0, 0, 0, 0, 0, 1, 1, 0, 0, 1])

In [ ]:
np.random.rand(10,20,9)

array([[[8.91230740e-01, 1.24775909e-01, 6.64905395e-01, ...,
         5.46692523e-01, 4.73262745e-01, 8.10702432e-01],
        [8.92332871e-01, 1.41317408e-01, 1.52338738e-01, ...,
         1.49462262e-01, 8.78540087e-01, 3.36949727e-01],
        [5.74406423e-01, 5.21175738e-01, 1.70363591e-01, ...,
         9.81596621e-01, 7.85398593e-01, 6.34754829e-01],
        ...,
        [9.16377965e-01, 3.77723903e-01, 4.10846587e-01, ...,
         4.81377566e-01, 8.43289965e-01, 2.46279444e-01],
        [2.04090833e-01, 4.23115027e-01, 6.15338985e-01, ...,
         1.07514258e-01, 6.03353475e-01, 1.85050585e-01],
        [7.86663963e-01, 5.78995660e-01, 9.82029951e-01, ...,
         6.80629606e-01, 5.96185519e-01, 4.54944200e-01]],

       [[9.44693150e-01, 8.09268926e-01, 7.56337489e-01, ...,
         2.42498929e-01, 7.64191838e-01, 6.26553297e-01],
        [3.24839259e-01, 5.56948472e-01, 2.09231757e-01, ...,
         7.68466519e-01, 4.66331452e-02, 4.37462749e-01],
        [9.55297858e-01, 

We can produce 1000 datapoints of a normally distributed data set by using np.random.normal()

In [ ]:
mu, sigma = 0, 0.1 # mean and standard deviation
s = np.random.normal(mu, sigma, 1000)


Exercise

Simulate a six-sided dice using numpy.random.choice(), generate a list of values you would obtain from 10 throws.

In [ ]:
dice_throw=np.random.choice([1,6],10)
print(dice_throw)

[6 1 6 1 6 1 1 1 1 6]


Simulate a two-sided coin toss that is NOT fair: it is twice as likely to have head than tails.

In [ ]:
coin_throw = np.random.choice(['Head',"Head",'Tail'],2)
print(coin_throw)

['Tail' 'Head']
